<!-- START of: finna - layout/Additions/general-post-head.phtml -->
<script src="https://unpkg.com/pdfobject@2.2.4/pdfobject.min.js"></script>
<script>
  $(document).ready(function() {
      console.log("redi");
      if (typeof pdfUrl === "undefined") {
        return;
      }
      var options = {
        page: 1,
        pdfOpenParams: {
          navpanes: false,
        }
      };



      const btn = $("<button class=\"pdf-btn\">Open PDF (native)</button>").click(function() {
        $(".recordcover-container").css({"width" :"100%", "height": "600px"});
        PDFObject.embed(pdfUrl, el);
        $(".pdf-btn").remove();
      });
      const el = $(".image-popup-trigger").parent().after(btn);

      const proxyUrl = VuFind.path + "/Cover/download?size=master&format=pdf&&id=" + recordId;
      const iframe = $("<iframe/>")
                   .attr("id", "pdf-js-viewer")
                   .attr("src", VuFind.path + "/themes/custom/js/pdfjs/web/viewer.html?" + proxyUrl)
                   .attr("frameborder", "0")
                   .attr("width", "100%")
                   .attr("height", "600");

      const btn2 = $("<button class=\"pdf-btn\">Open PDF (pdfjs)</button>").click(function() {
          el.replaceWith(iframe);
          $(".pdf-btn").remove();
      });
      $(".image-popup-trigger").parent().after(btn2);
  });
</script>
<!-- END of: finna - layout/Additions/general-post-head.phtml -->
